site_name: Uri Neri
site_url: https://urineri.github.io
site_author: Uri Neri
site_description: Personal academic website of Uri Neri

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - header.autohide
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: material/microscope

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/software.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/urineri
      name: Uri Neri on GitHub
    - icon: fontawesome/brands/twitter
      link: https://x.com/UriNeri2
      name: Uri Neri on Twitter
    - icon: fontawesome/brands/google
      link: https://scholar.google.com/citations?user=VComRgYAAAAJ
      name: Uri Neri on Google Scholar
    - icon: simple/bluesky
      link: https://bsky.app/profile/urineri.bsky.social
      name: Uri Neri on Bluesky

nav:
  - About: index.md
  - CV: cv.md
  - Publications: publications.md
  - Software: software.md
  - Blog: blog/index.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - tables
  - footnotes
  - def_list

plugins:
  - search
  - tags
  - blog:
      blog_dir: blog
      post_url_format: "{slug}"
      post_excerpt: required
      archive: true
      categories: true 